# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(default='default.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
