# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180606_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='%Y/%m/%d'),
        ),
    ]
