# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20180604_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('url', models.URLField(max_length=100, verbose_name='网址')),
                ('text', models.TextField(verbose_name='评论')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发表时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='评论文章')),
            ],
        ),
    ]
